import type { ProjectDetail } from "@/lib/types";

export const mockProjects: ProjectDetail[] = [
  {
    id: "demo-economic-impact-study",
    title: "Regional Economic Impact Study",
    assignedDate: "2026-03-01",
    lastUpdateDate: "2026-03-08",
    primaryDueDate: "2026-03-18",
    completedDate: null,
    priority: "High",
    status: "In Progress",
    percentComplete: 55,
    owner: "Isaac",
    departmentClient: "Montrose Group",
    nextAction: "Finalize county-level IMPLAN assumptions.",
    requestors: ["Director", "Client"],
    tools: ["IMPLAN", "Excel", "ArcGIS"],
    summary: "Prepare an impact study package with maps, assumptions, and a final memo.",
    notes: "Waiting on final employment assumptions from the client before the narrative is locked.",
    milestones: [
      {
        id: "milestone-1",
        projectId: "demo-economic-impact-study",
        name: "Draft assumptions reviewed",
        assignedBy: "Director",
        dueDate: "2026-03-10",
        status: "In Progress",
        priority: "High",
        notes: "Need confirmation on wage assumptions.",
        completedDate: null,
      },
      {
        id: "milestone-2",
        projectId: "demo-economic-impact-study",
        name: "Map package complete",
        assignedBy: "Client",
        dueDate: "2026-03-14",
        status: "Not Started",
        priority: "Medium",
        notes: "ArcGIS layout once final geography is confirmed.",
        completedDate: null,
      },
    ],
    updates: [
      {
        id: "update-1",
        projectId: "demo-economic-impact-study",
        updateDate: "2026-03-08",
        updatedField: "Primary Due Date",
        oldValue: "2026-03-15",
        newValue: "2026-03-18",
        reason: "Client requested an extra review round for assumptions.",
        enteredBy: "Isaac",
      },
    ],
    contacts: [
      {
        id: "contact-1",
        projectId: "demo-economic-impact-study",
        name: "Avery Collins",
        organization: "Client Team",
        role: "Client Contact",
        email: "avery@example.com",
        phone: "555-0100",
        notes: "Primary point of contact for data requests.",
      },
    ],
    projectNotes: [
      {
        id: "note-1",
        projectId: "demo-economic-impact-study",
        title: "Scope clarification",
        content: "Client confirmed they want county-level only for phase 1.",
        createdAt: "2026-03-05T12:00:00Z",
      },
    ],
  },
  {
    id: "demo-workforce-dashboard",
    title: "Workforce Dashboard Refresh",
    assignedDate: "2026-02-24",
    lastUpdateDate: "2026-03-05",
    primaryDueDate: "2026-03-12",
    completedDate: null,
    priority: "Urgent",
    status: "Waiting",
    percentComplete: 80,
    owner: "Isaac",
    departmentClient: "Internal",
    nextAction: "Review updated KPI definitions with leadership.",
    requestors: ["Manager"],
    tools: ["Excel", "Power BI", "SQL"],
    summary: "Refresh dashboard metrics and update exports for monthly reporting.",
    notes: "Blocked by revised KPI definitions.",
    milestones: [
      {
        id: "milestone-3",
        projectId: "demo-workforce-dashboard",
        name: "Leadership review",
        assignedBy: "Manager",
        dueDate: "2026-03-11",
        status: "Waiting",
        priority: "Urgent",
        notes: "Awaiting sign-off before final publishing.",
        completedDate: null,
      },
    ],
    updates: [
      {
        id: "update-2",
        projectId: "demo-workforce-dashboard",
        updateDate: "2026-03-05",
        updatedField: "Status",
        oldValue: "In Progress",
        newValue: "Waiting",
        reason: "Leadership requested a KPI definition review before completion.",
        enteredBy: "Isaac",
      },
    ],
    contacts: [
      {
        id: "contact-2",
        projectId: "demo-workforce-dashboard",
        name: "Jordan Diaz",
        organization: "Montrose Group",
        role: "Decision Maker",
        email: "jordan@example.com",
        phone: "555-0198",
        notes: "Approves dashboard release.",
      },
    ],
    projectNotes: [],
  },
];
